part of 'text_tool_controller.dart';

const Map<String, String> _htmlNamedEntities = {
  'AElig': 'Æ',
  'Aacute': 'Á',
  'Acirc': 'Â',
  'Agrave': 'À',
  'Alpha': 'Α',
  'Aring': 'Å',
  'Atilde': 'Ã',
  'Auml': 'Ä',
  'Beta': 'Β',
  'Ccedil': 'Ç',
  'Chi': 'Χ',
  'Dagger': '‡',
  'Delta': 'Δ',
  'ETH': 'Ð',
  'Eacute': 'É',
  'Ecirc': 'Ê',
  'Egrave': 'È',
  'Epsilon': 'Ε',
  'Eta': 'Η',
  'Euml': 'Ë',
  'Gamma': 'Γ',
  'GT': '>',
  'Iacute': 'Í',
  'Icirc': 'Î',
  'Igrave': 'Ì',
  'Iota': 'Ι',
  'Iuml': 'Ï',
  'Kappa': 'Κ',
  'LT': '<',
  'Lambda': 'Λ',
  'Mu': 'Μ',
  'Ntilde': 'Ñ',
  'Nu': 'Ν',
  'OElig': 'Œ',
  'Oacute': 'Ó',
  'Ocirc': 'Ô',
  'Ograve': 'Ò',
  'Omega': 'Ω',
  'Omicron': 'Ο',
  'Oslash': 'Ø',
  'Otilde': 'Õ',
  'Ouml': 'Ö',
  'Phi': 'Φ',
  'Pi': 'Π',
  'Prime': '″',
  'Psi': 'Ψ',
  'QUOT': '"',
  'Rho': 'Ρ',
  'Scaron': 'Š',
  'Sigma': 'Σ',
  'THORN': 'Þ',
  'Tau': 'Τ',
  'Theta': 'Θ',
  'Uacute': 'Ú',
  'Ucirc': 'Û',
  'Ugrave': 'Ù',
  'Upsilon': 'Υ',
  'Uuml': 'Ü',
  'Xi': 'Ξ',
  'Yacute': 'Ý',
  'Yuml': 'Ÿ',
  'Zeta': 'Ζ',
  'aacute': 'á',
  'acirc': 'â',
  'acute': '´',
  'aelig': 'æ',
  'agrave': 'à',
  'alefsym': 'ℵ',
  'alpha': 'α',
  'amp': '&',
  'and': '∧',
  'ang': '∠',
  'apos': "'",
  'aring': 'å',
  'asymp': '≈',
  'atilde': 'ã',
  'auml': 'ä',
  'bdquo': '„',
  'beta': 'β',
  'brvbar': '¦',
  'bull': '•',
  'cap': '∩',
  'ccedil': 'ç',
  'cedil': '¸',
  'cent': '¢',
  'chi': 'χ',
  'circ': 'ˆ',
  'clubs': '♣',
  'cong': '≅',
  'copy': '©',
  'crarr': '↵',
  'cup': '∪',
  'curren': '¤',
  'dArr': '⇓',
  'dagger': '†',
  'darr': '↓',
  'deg': '°',
  'delta': 'δ',
  'diams': '♦',
  'divide': '÷',
  'eacute': 'é',
  'ecirc': 'ê',
  'egrave': 'è',
  'empty': '∅',
  'emsp': '\u2003',
  'ensp': '\u2002',
  'epsilon': 'ε',
  'equiv': '≡',
  'eta': 'η',
  'eth': 'ð',
  'euml': 'ë',
  'euro': '€',
  'exist': '∃',
  'fnof': 'ƒ',
  'forall': '∀',
  'frac12': '½',
  'frac14': '¼',
  'frac34': '¾',
  'frasl': '⁄',
  'gamma': 'γ',
  'ge': '≥',
  'gt': '>',
  'hArr': '⇔',
  'harr': '↔',
  'hearts': '♥',
  'hellip': '…',
  'iacute': 'í',
  'icirc': 'î',
  'iexcl': '¡',
  'igrave': 'ì',
  'image': 'ℑ',
  'infin': '∞',
  'int': '∫',
  'iota': 'ι',
  'iquest': '¿',
  'isin': '∈',
  'iuml': 'ï',
  'kappa': 'κ',
  'lArr': '⇐',
  'lambda': 'λ',
  'lang': '〈',
  'laquo': '«',
  'larr': '←',
  'lceil': '⌈',
  'ldquo': '“',
  'le': '≤',
  'lfloor': '⌊',
  'lowast': '∗',
  'loz': '◊',
  'lrm': '\u200e',
  'lsaquo': '‹',
  'lsquo': '‘',
  'lt': '<',
  'macr': '¯',
  'mdash': '—',
  'micro': 'µ',
  'middot': '·',
  'minus': '−',
  'mu': 'μ',
  'nabla': '∇',
  'nbsp': '\u00a0',
  'ndash': '–',
  'ne': '≠',
  'ni': '∋',
  'not': '¬',
  'notin': '∉',
  'nsub': '⊄',
  'ntilde': 'ñ',
  'nu': 'ν',
  'oacute': 'ó',
  'ocirc': 'ô',
  'oelig': 'œ',
  'ograve': 'ò',
  'oline': '‾',
  'omega': 'ω',
  'omicron': 'ο',
  'oplus': '⊕',
  'or': '∨',
  'ordf': 'ª',
  'ordm': 'º',
  'oslash': 'ø',
  'otilde': 'õ',
  'otimes': '⊗',
  'ouml': 'ö',
  'para': '¶',
  'part': '∂',
  'permil': '‰',
  'perp': '⊥',
  'phi': 'φ',
  'pi': 'π',
  'piv': 'ϖ',
  'plusmn': '±',
  'pound': '£',
  'prime': '′',
  'prod': '∏',
  'prop': '∝',
  'psi': 'ψ',
  'quot': '"',
  'rArr': '⇒',
  'radic': '√',
  'rang': '〉',
  'raquo': '»',
  'rarr': '→',
  'rceil': '⌉',
  'rdquo': '”',
  'real': 'ℜ',
  'reg': '®',
  'rfloor': '⌋',
  'rho': 'ρ',
  'rlm': '\u200f',
  'rsaquo': '›',
  'rsquo': '’',
  'sbquo': '‚',
  'scaron': 'š',
  'sdot': '⋅',
  'sect': '§',
  'shy': '\u00ad',
  'sigma': 'σ',
  'sigmaf': 'ς',
  'sim': '∼',
  'spades': '♠',
  'sub': '⊂',
  'sube': '⊆',
  'sum': '∑',
  'sup': '⊃',
  'sup1': '¹',
  'sup2': '²',
  'sup3': '³',
  'supe': '⊇',
  'szlig': 'ß',
  'tau': 'τ',
  'there4': '∴',
  'theta': 'θ',
  'thetasym': 'ϑ',
  'thinsp': '\u2009',
  'thorn': 'þ',
  'tilde': '˜',
  'times': '×',
  'trade': '™',
  'uArr': '⇑',
  'uacute': 'ú',
  'uarr': '↑',
  'ucirc': 'û',
  'ugrave': 'ù',
  'uml': '¨',
  'upsih': 'ϒ',
  'upsilon': 'υ',
  'uuml': 'ü',
  'weierp': '℘',
  'xi': 'ξ',
  'yacute': 'ý',
  'yen': '¥',
  'yuml': 'ÿ',
  'zeta': 'ζ',
  'zwj': '\u200d',
  'zwnj': '\u200c',
};

_HtmlDecodeResult _decodeHtmlEntities(String input) {
  var changed = 0;
  var unknown = 0;
  final decoded = input.replaceAllMapped(
    RegExp(r'&(#x[0-9a-fA-F]+|#\d+|[a-zA-Z][a-zA-Z0-9]+);'),
    (match) {
      final entity = match.group(1)!;
      final char = _htmlEntityToChar(entity);
      if (char == null) {
        unknown++;
        return match.group(0)!;
      }
      changed++;
      return char;
    },
  );
  return _HtmlDecodeResult(
    value: decoded,
    changedCount: changed,
    unknownCount: unknown,
  );
}

String? _htmlEntityToChar(String entity) {
  if (entity.startsWith('#x') || entity.startsWith('#X')) {
    final code = int.tryParse(entity.substring(2), radix: 16);
    return code == null ? null : _safeCodePoint(code);
  }
  if (entity.startsWith('#')) {
    final code = int.tryParse(entity.substring(1));
    return code == null ? null : _safeCodePoint(code);
  }
  return _htmlNamedEntities[entity] ?? _htmlNamedEntities[entity.toLowerCase()];
}

String? _safeCodePoint(int code) {
  if (code < 0 || code > 0x10ffff) return null;
  if (code >= 0xd800 && code <= 0xdfff) return null;
  return String.fromCharCode(code);
}

String _encodeHtmlEntities(String input) {
  return input
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;')
      .replaceAll('\u00a0', '&nbsp;');
}

class _HtmlDecodeResult {
  const _HtmlDecodeResult({
    required this.value,
    required this.changedCount,
    required this.unknownCount,
  });

  final String value;
  final int changedCount;
  final int unknownCount;
}
